config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :posts do
 	 resources :comentarios
  end
  
  root :to => "posts#index"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comentario.rb
class Comentario < ApplicationRecord
  belongs_to :post

  	validates_presence_of :nome
	validates_presence_of :comentario
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comentarios

	validates_presence_of :titulo
	validates_presence_of :conteudo
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: [:show, :edit, :update, :destroy]

  # GET /comentarios
  # GET /comentarios.json
  def index
    @post = Post.find(params[:post_id])
    @comentarios = @post.comentarios

  end



  # GET /comentarios/new
  def new
    @post = Post.find(params[:post_id])
    @comentario = @post.comentarios.new
  end

  

  # POST /comentarios
  # POST /comentarios.json
  def create
    @post = Post.find(params[:post_id])
    @comentario = @post.comentarios.new(comentario_params)

    
      if @comentario.save
        @post01 = Post.find(@comentario.post_id)
        redirect_to post_comentarios_path(@post), notice: 'Comentário gravado com sucesso!'
      else
        render :new
      end
    
  end

  # PATCDELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario.destroy
    respond_to do |format|
        @post01 = Post.find(@comentario.post_id)
        format.html { redirect_to @post01, notice: 'Comentario foi removido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentario_params
      params.require(:comentario).permit(:nome, :comentario, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  @comentarios = Comentario.all
  @comentario = Comentario.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post criado com sucesso.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.new(post_params)
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post foi removido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:titulo, :conteudo, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comentarios/_form.html.erb
      <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" style="color: black">Autor: Felipe Henrique</a>
            </div>
        </div>


  </nav>





  <!--Header -->
    <header class="intro-header" style="background-image: url('http://www.rubyinside.com/advent2006/wallpaper1920.jpg')">
        <div class="container" style="height: 400px">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading" style="text-align: center;">
                        <h1 >Blog Ruby On Rails</h1>
                        <hr class="small">
                        <span class="subheading">Desenvolvimento em Ruby On Rails</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->


    <!-- Main Content -->
    <div class="container">
        <div class="row">
                  <h1 class="post-title" style="text-align: center">COMENTÁRIOS</h1>
                  <hr>
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-preview" style="text-align: center">
                    <%= form_with(model: [@post, @comentario], local: true) do |form| %>
                                              <% if comentario.errors.any? %>
                                                <div id="error_explanation">
                                                  <h2><%= pluralize(comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

                                                  <ul>
                                                  <% comentario.errors.full_messages.each do |message| %>
                                                    <li><%= message %></li>
                                                  <% end %>
                                                  </ul>
                                                </div>
                                              <% end %>

                                              <div class="field">
                                                <%= form.label :nome %>
                                                <%= form.text_field :nome, id: :comentario_nome %>
                                              </div>

                                              <div class="field">
                                                <%= form.label :comentario %>
                                                <%= form.text_area :comentario, id: :comentario_comentario %>
                                              </div>


                                              <div class="actions">
                                                <%= form.submit %>
                                              </div>
                                            <% end %> 
                              
                                              
                </div>
            </div>
        </div>
     </div>

                   
                   
                
                
                <hr>
                
                <hr>
                <div type="button" class="btn btn-default navbar-btn"><%= link_to 'New Post', new_post_path %></div>
                <div type="button" class="btn btn-default navbar-btn"><%= link_to 'Back', post_path(@post) %></div>
      

     <!-- Footer -->
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                        <ul class="list-inline text-center">
                            <li>
                                <a href="#">
                                    <span class="fa-stack fa-lg">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="fa-stack fa-lg">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                   </span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="fa-stack fa-lg">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <p class="copyright text-muted">Copyright &copy; Felipe Henrique Monteiro da Silveira 2017</p>
                    </div>
                </div>
            </div>
        </footer>

app/views/comentarios/index.html.erb
    
  

      <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" style="color: black">Autor: Felipe Henrique</a>
            </div>
        </div>


  </nav>





  <!--Header -->
    <header class="intro-header" style="background-image: url('http://www.rubyinside.com/advent2006/wallpaper1920.jpg')">
        <div class="container" style="height: 400px">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading" style="text-align: center;">
                        <h1 >Blog Ruby On Rails</h1>
                        <hr class="small">
                        <span class="subheading">Desenvolvimento em Ruby On Rails</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->


    <!-- Main Content -->
    <div class="container">
        <div class="row">
                  <h1 class="post-title" style="text-align: center">COMENTÁRIOS</h1>
                  <hr>
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-preview">

                      <% if @comentarios.size > 0%>
                        <% @comentarios.reverse.each do |comentario| %>
                          <h2 class="post-title">
                              <%= comentario.nome %>
                          </h2>
                          
                          <h3 class="post-subtitle">
                               <%= comentario.comentario %>
                          </h3>
                          <p class="post-meta"><%= time_ago_in_words(comentario.created_at) %></p> 
                          <hr>
                      <%end%> 
                    
          
                         <%end%> 
                </div>
                                <hr>
                
                <hr>
                  <div type="button" class="btn btn-default navbar-btn"><%= link_to 'New Post', new_post_path %></div>
                  <div type="button" class="btn btn-default navbar-btn"><%= link_to 'Back', post_path(@post) %></div>
            </div>

           </div>

       </div>


      

     <!-- Footer -->
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                        <ul class="list-inline text-center">
                            <li>
                                <a href="#">
                                    <span class="fa-stack fa-lg">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="fa-stack fa-lg">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                   </span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="fa-stack fa-lg">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <p class="copyright text-muted">Copyright &copy; Felipe Henrique Monteiro da Silveira 2017</p>
                    </div>
                </div>
            </div>
        </footer>

app/views/comentarios/new.html.erb
<p id="notice"><%= notice %></p>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Back', posts_path %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @comentario.nome %>
</p>

<p>
  <strong>Comentario:</strong>
  <%= @comentario.comentario %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comentario.post %>
</p>

<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AgoraVai</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" style="color: black">Autor: Felipe Henrique</a>
            </div>
        </div>

  </nav>





  <!--Header -->
    <header class="intro-header" style="background-image: url('http://www.rubyinside.com/advent2006/wallpaper1920.jpg')">
        <div class="container" style="height: 400px">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading" style="text-align: center;">
                        <h1 >Blog Ruby On Rails</h1>
                        <hr class="small">
                        <span class="subheading">Desenvolvimento em Ruby On Rails</span>
                    </div>
                </div>
            </div>
        </div>
    </header>



    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->



    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-preview">
                    
                        <h2 class="post-title">
                        <%= form_with(model: post, local: true, html: { multipart: true } ) do |form| %>
                          <% if post.errors.any? %>
                            <div id="error_explanation">
                              <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

                              <ul>
                              <% post.errors.full_messages.each do |message| %>
                                <li><%= message %></li>
                              <% end %>
                              </ul>
                            </div>
                          <% end %>

                          <div class="field">
                            <%= form.label :titulo %>
                            <%= form.text_field :titulo, id: :post_titulo %>
                          </div>

                          <div class="field">
                            <%= form.label :conteudo %>
                            <%= form.text_area :conteudo, id: :post_conteudo %>
                          </div>

                          <div class="actions">
                            <%= form.submit %>
                          </div>
                          
                          <div class="field">
                            <%= form.label :avatar %>
                            <%= form.file_field :avatar %>
                          </div>

                          
                        <% end %>
                        </h2>
                     
               </div>
            </div>
         </div>
      </div>


     <!-- Footer -->
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                        <ul class="list-inline text-center">
                            <li>
                                <a href="#">
                                    <span class="fa-stack fa-lg">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="fa-stack fa-lg">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                   </span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="fa-stack fa-lg">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <p class="copyright text-muted">Copyright &copy; Felipe Henrique Monteiro da Silveira 2017</p>
                    </div>
                </div>
            </div>
        </footer>

app/views/posts/edit.html.erb
<%= render 'form', post: @post %>

 

                <div type="button" class="btn btn-default navbar-btn">
                <%= link_to 'Show', @post %>
                </div>


                <div type="button" class="btn btn-default navbar-btn">
                <%= link_to 'Back', posts_path %>
                </div>

app/views/posts/index.html.erb
    
      <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <a class="navbar-brand" style="color: black">Autor: Felipe Henrique</a>
            </div>
                <button type="button" class="btn btn-default navbar-btn" style="float: right; color: red">
                <%= link_to 'Administrador', new_admin_user_session_path %>
                </button> 
        </div>


  
  





  <!--Header -->
    <header class="intro-header" style="background-image: url('http://www.rubyinside.com/advent2006/wallpaper1920.jpg')">
        <div class="container" style="height: 400px">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading" style="text-align: center;">
                        <h1 >Blog Ruby On Rails</h1>
                        <hr class="small">
                        <span class="subheading">Desenvolvimento em Ruby On Rails</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->




    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-preview">
                    
                      <% @posts.reverse.each do |post| %>
                        <h2 class="post-title">
                            <%= link_to post.titulo, post %>
                        </h2>
                        
                        <h3 class="post-subtitle">
                             <%= post.conteudo %></h3>
                    
                    
                    <p class="post-meta">Posted: <%= time_ago_in_words(post.created_at) %>  <%= link_to 'Edit', edit_post_path(post) %></p> 
                    <hr>
                    <% end %>
                </div>
                
                <hr>
                
                <hr>
                <div type="button" class="btn btn-default navbar-btn"><%= link_to 'New Post', new_post_path %></div>
      

     <!-- Footer -->
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                        <ul class="list-inline text-center">
                            <li>
                                <a href="#">
                                    <span class="fa-stack fa-lg">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="fa-stack fa-lg">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                   </span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="fa-stack fa-lg">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <p class="copyright text-muted">Copyright &copy; Felipe Henrique Monteiro da Silveira 2017</p>
                    </div>
                </div>
            </div>
        </footer>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>


                <div type="button" class="btn btn-default navbar-btn">
                <%= link_to 'Back', posts_path %>
                </div>

app/views/posts/show.html.erb
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" style="color: black">Autor: Felipe Henrique</a>
            </div>
        </div>


  





  <!--Header -->
    <header class="intro-header" style="background-image: url('http://www.rubyinside.com/advent2006/wallpaper1920.jpg')">
        <div class="container" style="height: 400px">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading" style="text-align: center;">
                        <h1 >Blog Ruby On Rails</h1>
                        <hr class="small">
                        <span class="subheading">Desenvolvimento em Ruby On Rails</span>
                    </div>
                </div>
            </div>
        </div>
    </header>


    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->



    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-preview">
                    
                        <h2 class="post-title">
                       <%= @post.titulo %>
                       <hr>
                       </h2>
                       <h4>Imagem:</h4>
                       <%= image_tag @post.avatar.url(:medium) %>
                        
                         <hr>
                        <h3 class="post-subtitle">
                             <%= @post.conteudo %></h3>
                    <hr>

	                <div type="button" class="btn btn-default navbar-btn"><%= link_to 'Apagar POST', @post, method: :delete, data: { confirm: 'Are you sure?' } %></div>

                    

                </div>

				<hr>
							<h1>Comentarios</h1>
							<hr>

								<% @comentarios.each do |x|%>
									<%if x.post_id == @post.id%>
										<h4><%= x.nome%><br></h4>
										<em><%= x.comentario%></em>
										<hr style="background-color: red">
									<%end%>
								<%end%>

							<hr>


							

				<div type="button" class="btn btn-default navbar-btn">				
					<%= link_to 'Novo Comentário', new_post_comentario_path(@post)%> 
				</div>


				<div type="button" class="btn btn-default navbar-btn">
					<%= link_to pluralize(@post.comentarios.size, 'Comentário', 'Comentários'), post_comentarios_path(@post)%> 
                </div>	



                <hr>



	
              <div type="button" class="btn btn-default navbar-btn">
                <%= link_to 'Edit', edit_post_path(@post) %> 
                </div>

                <div type="button" class="btn btn-default navbar-btn">
                <%= link_to 'Back', posts_path %> 
                </div>


                <hr>
                <div type="button" class="btn btn-default navbar-btn">
                <%= link_to 'New Post', new_post_path %>
                </div>
                     
      

     <!-- Footer -->
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                        <ul class="list-inline text-center">
                            <li>
                                <a href="#">
                                    <span class="fa-stack fa-lg">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="fa-stack fa-lg">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                   </span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="fa-stack fa-lg">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <p class="copyright text-muted">Copyright &copy; Felipe Henrique Monteiro da Silveira 2017</p>
                    </div>
                </div>
            </div>
        </footer>